### PR TITLE
[AV-229] model solid motor thrust curve

### PR DESCRIPTION
**Pull request by rishivg**
Simple function to get our current thrust from a csv file (in the folder thrust_data)

### CODE REVIEW

**Comment by AyberkY** [comment]
whoa. Not a code review yet, but a few things I wanna point out:
- There's a crap ton of files in the diff. Makes it difficult to see what you actually worked on. Please add unnecessary directories like `.vs` and `build/` to the `.gitignore` file so they don't show up.
- If you could, please rename the PR to include the Trello ticket in brackets like "[AV-420] Go To Space"
- Just nit picking here, but I don't think this should be a feature branch. I wouldn't worry about changing it since you're already at a PR, but keep in mind for the future.

**Comment by NPIPHI** [comment]
- Avoid loading the csv in the get thrust function. Loading the whole csv is pretty slow. You can put the csv as a member variable and then load it in the constructor of solid motor. Same with loading columns into vector<double>.
- Be sure to handle the case where timestamp <  time_vals[i] I don't think it should ever happen but we shouldn't be segfaulting if it does.

**Comment by AyberkY** [comment]
[[AV-229] Model solid motor thrust curve](https://trello.com/c/LpRLx6Lf/229-av-229-model-solid-motor-thrust-curve)

**Comment by AyberkY** [comment]
Performed a major refactor of the Propulsion classes:

- Broke up the `SolidMotor` class into a `RocketMotor` base class and two derived classes called `ConstantThrustSolidMotor` and `ThrustCurveSolidMotor` to distinguish between the two.
- Reason for this was to keep the constant thrust motor object for quick&dirty simulations
- Rewrote data parsing to only happen in the constructor instead of every `current_thrust` call. Parsed data is saved in a Eigen matrix member variable of the ThrustCurve motor class.

**Comment by rishivg** [comment]
All of the logic for changing a constant thrust solid motor to a thrust curve solid motor looks sound. I also think the new naming scheme makes a lot of sense moving forward (incase we want to use other motors), and importing the CSV file into an Eigen matrix is definitely a good idea. From what I can see, the is_burning function isn't implemented anywhere at the moment, but the logic for that checks out as well. Id say just add comments to that function, and the merge looks good to me.

**Pull request merged**
