### PR TITLE
Includes Directory

### PR DESCRIPTION
**Pull request by mjacob1002**
Moved the header files to an includes folder in order to better organize the project. I also edited the CMakeLists.txt file in order to still include it in the targets.

### CODE REVIEW

**Review by NPIPHI — CHANGES_REQUESTED** [review]
In the cmake lists you need to remove all the .h files from the add_executable function since you moved all the .h files to a separate directory.

**Comment by NPIPHI** [comment]
Also don't set a src variable in the cmake files, use the CMAKE_SOURCE_DIR variable to get the path. The include_directories call is using ${SRC}/includes when it should use ${CMAKE_SOURCE_DIR}/includes

**Comment by mjacob1002** [comment]
Should have addressed the issues - let me know if you find other issues.

**Comment by mjacob1002** [comment]
Should have addressed the issues - let me know if you find other issues.

**Review by NPIPHI — APPROVED** [review]

**Comment by NPIPHI** [comment]
LGTM

**Pull request merged**
